/**
 * Traduction des libellés de l'assistant.
 *
 * Les quinze schémas décrivent leurs sections et leurs champs en français,
 * au plus près de la définition : y intercaler des clefs d'i18n rendrait ces
 * fichiers illisibles pour un gain nul, puisqu'on les lit toujours dans une
 * langue. La table ci-dessous traduit donc **par la chaîne source**, comme le
 * fait gettext — la version française est la clef.
 *
 * Une chaîne absente de la table est rendue telle quelle : c'est ce qui
 * convient aux fragments qui n'ont pas de langue (« 0..* », « Class »,
 * « application.jar », une date d'exemple), et ce qui évite qu'un libellé
 * nouvellement ajouté fasse disparaître le texte au lieu de le laisser en
 * français.
 *
 * `tests/unit/assistant.test.ts` vérifie que chaque clef correspond bien à une
 * chaîne réellement présente dans un schéma : une apostrophe typographique
 * recopiée de travers passerait sinon inaperçue.
 */

import type { Language } from '../i18n';

export const LIBELLES_EN: Readonly<Record<string, string>> = {
  "Diagramme de classes": "Class diagram",
  "Diagramme d'objets": "Object diagram",
  "Diagramme de composants": "Component diagram",
  "Diagramme de déploiement": "Deployment diagram",
  "Diagramme de paquetages": "Package diagram",
  "Diagramme de structure composite": "Composite structure diagram",
  "Diagramme de profil": "Profile diagram",
  "Diagramme de cas d'utilisation": "Use case diagram",
  "Diagramme de séquence": "Sequence diagram",
  "Diagramme de communication": "Communication diagram",
  "Diagramme d'activité": "Activity diagram",
  "Diagramme d’états-transitions": "State machine diagram",
  "Diagramme de temps": "Timing diagram",
  "Vue d'ensemble des interactions": "Interaction overview diagram",
  "Diagramme de Gantt": "Gantt chart",
  "Nom": "Name",
  "Type": "Type",
  "N°": "No.",
  "Libellé": "Label",
  "Rôle": "Role",
  "Relation": "Relationship",
  "Relations": "Relationships",
  "De": "From",
  "Vers": "To",
  "Classe": "Class",
  "Classes": "Classes",
  "Attributs": "Attributes",
  "Méthodes": "Methods",
  "Classe abstraite": "Abstract class",
  "Énumération": "Enumeration",
  "Valeurs": "Values",
  "Objets": "Objects",
  "Propriétés": "Properties",
  "Composant": "Component",
  "Composants": "Components",
  "Interface": "Interface",
  "Interfaces": "Interfaces",
  "Fournie par": "Provided by",
  "Utilise": "Uses",
  "Utilisations": "Usages",
  "Nœud": "Node",
  "Nœuds": "Nodes",
  "Artefacts": "Artefacts",
  "Déployé sur": "Deployed on",
  "Connexions": "Connections",
  "Protocole": "Protocol",
  "Paquetages": "Packages",
  "Contenu dans": "Contained in",
  "Dépendances": "Dependencies",
  "Dépend de": "Depends on",
  "Classe englobante": "Enclosing class",
  "Parties": "Parts",
  "Connecteurs": "Connectors",
  "Stéréotype": "Stereotype",
  "Stéréotypes": "Stereotypes",
  "Élément": "Element",
  "Acteur": "Actor",
  "Cas d'utilisation": "Use cases",
  "Cas": "Use case",
  "Hérite de": "Inherits from",
  "Système": "System",
  "Participant": "Participant",
  "Participants": "Participants",
  "Message": "Message",
  "Messages": "Messages",
  "Représentation": "Representation",
  "Synchrone": "Synchronous",
  "Asynchrone": "Asynchronous",
  "Retour": "Return",
  "Ligne de vie": "Lifeline",
  "Lignes de vie": "Lifelines",
  "Liens": "Links",
  "Étapes": "Steps",
  "Action": "Action",
  "Décision": "Decision",
  "Condition": "Condition",
  "Couloir": "Swimlane",
  "Actions parallèles": "Parallel actions",
  "Si oui / branche 1": "If yes / branch 1",
  "Si non / branche 2": "If no / branch 2",
  "État": "State",
  "États": "States",
  "États nommés": "Named states",
  "État final": "Final state",
  "Premier état": "First state",
  "Transitions": "Transitions",
  "Déclencheur": "Trigger",
  "Changements d’état": "State changes",
  "Instant": "Time",
  "Fragment": "Fragment",
  "Fragments": "Fragments",
  "Enchaînement": "Sequencing",
  "Ligne compacte": "Compact line",
  "En attente": "Waiting",
  "Principal": "Primary",
  "Secondaire (service externe)": "Secondary (external service)",
  "Cas sans acteur direct": "Use cases without a direct actor",
  "Relations entre cas": "Relationships between use cases",
  "Acteurs et leurs cas d’utilisation": "Actors and their use cases",
  "inclut (toujours)": "includes (always)",
  "étend (parfois)": "extends (sometimes)",
  "Agrégation": "Aggregation",
  "Composition": "Composition",
  "Association": "Association",
  "Dépendance": "Dependency",
  "Réalisation": "Realization",
  "Héritage (la cible hérite de la source)": "Inheritance (target inherits from source)",
  "Cardinalité de départ": "Source multiplicity",
  "Cardinalité d'arrivée": "Target multiplicity",
  "Nature": "Kind",
  "Frontière": "Boundary",
  "Contrôle": "Control",
  "Service": "Service",
  "Projet": "Project",
  "Phase": "Phase",
  "Phases": "Phases",
  "Début": "Start",
  "Fin": "End",
  "Avancement (%)": "Progress (%)",
  "Jalon": "Milestone",
  "Jalons": "Milestones",
  "À la fin de": "At the end of",
  "Jours non travaillés": "Non-working days",
  "Jour": "Day",
  "Échelle": "Scale",
  "Jours": "Days",
  "Semaines": "Weeks",
  "Mois": "Months",
  "Le cadre qui délimite le périmètre étudié.": "The frame that bounds the scope under study.",
  "Un acteur par ligne, avec tout ce qu'il fait dans le système — un cas par ligne. Ce qu'il hérite n'a pas à être répété : la généralisation le lui donne déjà.": "One actor per line, with everything they do in the system — one use case per line. What they inherit need not be repeated: generalisation already grants it.",
  "Ceux qu'aucun acteur ne déclenche lui-même : ils ne sont atteints que par « inclut » ou « étend ».": "Those no actor triggers directly: they are only reached through “includes” or “extends”.",
  "Chaque ligne relie deux éléments déclarés au-dessus.": "Each line links two elements declared above.",
  "Une par ligne. Préfixez les membres de + - # pour la visibilité.": "One per line. Prefix members with + - # for visibility.",
  "Une instance nommée, sa classe, et la valeur de ses attributs.": "A named instance, its class, and its attribute values.",
  "Le service offert par un composant, que les autres consomment.": "The service a component offers, which others consume.",
  "Ce qui est déployé : exécutables, archives, bases.": "What is deployed: executables, archives, databases.",
  "Les machines et environnements d’exécution.": "Machines and runtime environments.",
  "Laissez « Contenu dans » vide pour un paquetage de premier niveau.": "Leave “Contained in” empty for a top-level package.",
  "Une seule ligne : la structure dont on détaille l’intérieur.": "A single line: the structure whose inside is detailed.",
  "Les composants internes, avec leur rôle.": "Inner components, with their role.",
  "Les extensions du métamodèle, et ce qu’elles étendent.": "Metamodel extensions, and what they extend.",
  "Les éléments qui portent un stéréotype.": "Elements carrying a stereotype.",
  "Dans l’ordre chronologique, de haut en bas.": "In chronological order, top to bottom.",
  "Chaque fragment renvoie à un diagramme de séquence existant.": "Each fragment refers to an existing sequence diagram.",
  "Le numéro donne l’ordre : 1, 1.1, 2…": "The number gives the order: 1, 1.1, 2…",
  "Dans l’ordre d’exécution. Une décision ouvre deux branches, décrites dans les deux dernières colonnes.": "In execution order. A decision opens two branches, described in the last two columns.",
  "Dans l’ordre. Une condition ouvre une alternative.": "In order. A condition opens an alternative.",
  "Le premier état déclaré est atteint depuis l’état initial.": "The first state declared is reached from the initial state.",
  "L’ordre de déclaration fixe l’ordre des colonnes.": "Declaration order fixes the column order.",
  "L’instant est un nombre : 0, 100, 200…": "Time is a number: 0, 100, 200…",
  "La date de début est facultative : laissée vide, elle est prise sur la phase la plus précoce.": "The start date is optional: left empty, it is taken from the earliest phase.",
  "Les phases sont déjà là : renseignez leur période, au format AAAA-MM-JJ. Deux phases peuvent se chevaucher — la rédaction du rapport court souvent en parallèle.": "The phases are already there: fill in their period, formatted YYYY-MM-DD. Two phases may overlap — report writing often runs in parallel.",
  "Un point de contrôle sans durée : il se pose à la fin d'une phase.": "A checkpoint without duration: it sits at the end of a phase.",
  "Facultatif : un jour de la semaine — samedi, dimanche — ou une date précise. Les barres sont alors coupées d’une zone grisée, sans changer de période.": "Optional: a weekday — Saturday, Sunday — or a specific date. Bars are then split by a greyed area, without changing their period.",
  "Client inscrit": "Registered customer",
  "Plateforme de réservation": "Booking platform",
  "S'authentifier": "Authenticate",
  "Réserver une prestation\nAnnuler une réservation": "Book a service\nCancel a booking",
  "Vérifier la disponibilité": "Check availability",
  "Réservation": "Booking",
  "Commande": "Order",
  "Facturation": "Billing",
  "Authentifier": "Authenticate",
  "Interface web": "Web front end",
  "Base de données": "Database",
  "Serveur applicatif": "Application server",
  "Applications": "Applications",
  "API commande": "Order API",
  "Service commercial": "Sales department",
  "Confirmer": "Confirm",
  "Refuser": "Reject",
  "paiement reçu": "payment received",
  "authentifié": "authenticated",
  "passe": "passes",
  "metier": "business",
  "lignes": "lines",
  "Analyse du projet": "Project analysis",
  "Soutenance": "Defence",
  "Projet de fin d’études": "Final-year project",
  "samedi": "saturday",
  "AAAA-MM-JJ": "YYYY-MM-DD",
  "Étend": "Extends",
  "Entité": "Entity",
  "réserver()": "book()",
  "confirmer()": "confirm()",
  "commande12": "order12",
  "LigneCommande": "OrderLine",
};

/** Libellé d'un schéma dans la langue de l'interface. */
export function textOf(texte: string, language: Language): string {
  return language === 'en' ? (LIBELLES_EN[texte] ?? texte) : texte;
}
